export const constants = {
  ADD_DATA: "ADD_DATA",
  STORE_DATA: "STORE_DATA",
  DELETE_DATA: "DELETE_DATA",
  UPDATE_DATA: "UPDATE_DATA",

  ADD_CARD: "ADD_CARD",
  STORE_CARD: "STORE_CARD",
  DELETE_CARD: "DELETE_CARD",
  UPDATE_CARD: "UPDATE_CARD",

  ADD_RECURRENCE: "ADD_RECURRENCE",
  UPDATE_RECURRENCE: "UPDATE_RECURRENCE",
  DELETE_RECURRENCE: "DELETE_RECURRENCE",
  STORE_RECURRENCE: "STORE_RECURRENCE",

  ADD_GROUPS: "ADD_GROUPS",
  DELETE_GROUPS: "DELETE_GROUPS",
  STORE_GROUPS: "STORE_GROUPS",

  ADD_SECTIONS: "ADD_SECTIONS",
  DELETE_SECTIONS: "DELETE_SECTIONS",
  STORE_SECTIONS: "STORE_SECTIONS"
};
